name: isolate_classy
description: It makes very easy and elegant for your asynchronous functions to run on isolate.
version: 1.0.1
repository: https://github.com/gold-duo/isolate_classy

platforms:
  android:
  ios:
  macos:
  linux:
  windows:

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
